/**
 * You are given two strings s and t.
 *
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 *
 * Return the letter that was added to t.
 */
const findTheDifference = (s, t) => {
    if (s == null || s.length === 0) {
        return t.charAt(0);
    }
    let c = s[0].charCodeAt() ^ t[0].charCodeAt();
    for (let i = 1; i < s.length; i++) {
        c ^= s[i].charCodeAt() ^ t[i].charCodeAt(); 
    }
    c ^= t[t.length - 1].charCodeAt();
    return String.fromCharCode(c);
};

console.log(findTheDifference("abcd", "abcde"));
console.log(findTheDifference("", "y"));
console.log(findTheDifference("a", "aa"));
console.log(findTheDifference("ae", "aea"));