/**
 * You are given two strings s and t.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Return the letter that was added to t.
 */
public class FindTheDifference {
    
    private static char findTheDifference(String s, String t) {
        if (s == null || s.isEmpty()) {
            return t.charAt(0);
        }
        int c = s.charAt(0) ^ t.charAt(0);
        for (int i = 1; i < s.length(); i++) {
            c ^= s.charAt(i) ^ t.charAt(i);
        }
        c ^= t.charAt(t.length() - 1);
        return (char)c;
    }

    public static void main(String[] args) {
        System.out.println(findTheDifference("abcd", "abcde"));
        System.out.println(findTheDifference("", "y"));
        System.out.println(findTheDifference("a", "aa"));
        System.out.println(findTheDifference("ae", "aea"));
    }
}
