"""
You are given two strings, s and t which only consist of lowercase letters. 
t is generated by shuffling the letters in s as well as potentially adding an additional random character. 
Return the letter that was randomly added to t if it exists, otherwise, return ’ ‘.
Note: You may assume that at most one additional character can be added to t.
"""


class FindTheDifference:
    def findTheDifference(self, s: str, t: str) -> str:
        if s == None or len(s) == 0:
            return t[0]
        c = ord(s[0]) ^ ord(t[0])
        for i in range(1, len(s)):
            c ^= ord(s[i]) ^ ord(t[i])
        c ^= ord(t[len(t) - 1])
        return chr(c)


if __name__ == "__main__":
    f = FindTheDifference()
    print(f.findTheDifference("abcd", "abcde"))
    print(f.findTheDifference("", "y"))
    print(f.findTheDifference("a", "aa"))
    print(f.findTheDifference("ae", "aea"))
